name = "votekick-bot"
main = "index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
BASE_VOTE_THRESHOLD = "20"
VOTE_DURATION_SECONDS = "300"
INITIATOR_COOLDOWN_SECONDS = "60"
TARGET_COOLDOWN_SECONDS = "180"
MIN_WEIGHT_TO_INITIATE = "1.0"
ENABLE_VERIFICATION = "1"

[[d1_databases]]
binding = "DB"
database_name = "votekick-db"
database_id = "0a3f213d-dc3c-4bb3-86dc-0b3fc896322e"

[triggers]
crons = ["*/1 * * * *"]
